name: Auto-Clean

on:
  #自动清理：每天早上6点
  #schedule:
    #- cron: 0 22 * * *
  #手动清理
  workflow_dispatch:
    inputs:
      NUMBER:
        default: '0'
        required: false
        type: string

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: ${{inputs.NUMBER || '0'}}
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0
