#CI项目名
name: Mediatek-Immortal

on:
  #自动编译：每天早上4点
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-CORE.yml
    with:
      #编译平台
      OWRT_TARGET: Mediatek
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: OWRT
      #默认密码，仅作展示，请勿乱改
      OWRT_PW: 无
      #默认地址
      OWRT_IP: 192.168.10.1
      #默认源码
      OWRT_URL: https://github.com/immortalwrt/immortalwrt.git
      #默认分支
      OWRT_BRANCH: master
