#CI项目名
name: Mediatek-Immortal

on:
  #自动编译：每天早上4点
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  Upsing:
    #自动在每次构建前检查sing-box是否有更新
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Update sing-box version
        run: |
          chmod +x ./Scripts/Upsing.sh
          ./Scripts/Upsing.sh

      - name: Commit changes
        id: commit-changes
        run: |
          if [ -n "$(git status --porcelain ./Scripts/Packages.sh)" ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update sing-box version"
          echo "singupdated=true" >> $GITHUB_OUTPUT
          else
            echo "No sing update"
          fi     
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit-changes.outputs.singupdated == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
  wrt_config:
    needs: Upsing
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: Mediatek
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/immortalwrt/immortalwrt.git
      #默认分支
      WRT_BRANCH: master
