name: OpenWRT-TEST  #设备型号，请用大写字母，请勿乱写

on:
  push:

env:
  DEVICE_NAME: TEST  #设备型号，请用大写字母，请勿乱写
  DEVICE_TYPE: arm64  #设备内核类型，请用小写字母，请勿乱写
  DEVICE_IP: 192.168.2.1  #设备默认登陆地址
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_openwrt:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt -y update
          sudo -E apt -y purge azure* docker* dotnet* firefox* ghc* google* llvm* moby* mongodb* mysql* openjdk* php* powershell* snap* zulu*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install dos2unix ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt -y autoremove --purge
          sudo -E apt -y clean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Check Projects
        uses: actions/checkout@v3

      - name: Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch https://github.com/coolsnowwolf/lede.git

      - name: Custom package
        run: |
          cd ./lede/package

          #Design Theme
          git clone --depth=1 --single-branch https://github.com/gngpp/luci-theme-design.git
          #Design Config
          git clone --depth=1 --single-branch https://github.com/gngpp/luci-app-design-config.git
          #OpenClash
          git clone --depth=1 --single-branch --branch "dev" https://github.com/vernesong/OpenClash.git

          #OpenClash Core
          export CORE_VER=https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/core_version
          export CORE_TUN=https://github.com/vernesong/OpenClash/raw/core/dev/premium/clash-linux
          export CORE_DEV=https://github.com/vernesong/OpenClash/raw/core/dev/dev/clash-linux
          export CORE_MATE=https://github.com/vernesong/OpenClash/raw/core/dev/meta/clash-linux

          cd ./OpenClash/luci-app-openclash/root/etc/openclash
          mkdir ./core && cd ./core

          export TUN_VER=$(curl -sfL $CORE_VER | sed -n "2p")
          curl -sfL -o ./tun.gz "$CORE_TUN"-"$DEVICE_TYPE"-"$TUN_VER".gz
          gzip -d ./tun.gz
          mv ./tun ./clash_tun

          curl -sfL -o ./meta.tar.gz "$CORE_MATE"-"$DEVICE_TYPE".tar.gz
          tar -zxf ./meta.tar.gz
          mv ./clash ./clash_meta

          curl -sfL -o ./dev.tar.gz "$CORE_DEV"-"$DEVICE_TYPE".tar.gz
          tar -zxf ./dev.tar.gz

          chmod +x ./clash*
          rm -rf ./*.gz

      - name: Update Feeds
        run: |
          cd ./lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom sed
        run: |
          cd ./lede

          #默认主机名
          sed -i "s/OpenWrt/$DEVICE_NAME/g" ./package/base-files/files/bin/config_generate
          #默认IP地址
          sed -i "s/192.168.1.1/$DEVICE_IP/g" ./package/base-files/files/bin/config_generate
          #默认主题
          sed -i 's/luci-theme-bootstrap/luci-theme-design/g' ./feeds/luci/collections/luci/Makefile
          #默认时间格式
          sed -i 's/os.date()/os.date("%Y-%m-%d %H:%M:%S %A")/g' $(find ./package/lean/autocore/files/ -type f -name "index.htm")

      - name: Custom Settings
        run: |
          cd ./lede

          rm -rf ./tmp && rm -rf ./.config*
          cat >> .config << EOF
          #设置设备
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r4s=y
          #增加参数
          CONFIG_TARGET_KERNEL_PARTSIZE=64
          CONFIG_TARGET_ROOTFS_PARTSIZE=512
          #删除参数
          CONFIG_TARGET_ROOTFS_EXT4FS=n
          #增加组件
          CONFIG_PACKAGE_autosamba=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_ip6tables-extra=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          #增加主题
          CONFIG_PACKAGE_luci-theme-design=y
          CONFIG_PACKAGE_luci-app-design-config=y
          #增加插件
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-turboacc=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-uugamebooster=y
          EOF

          make defconfig

      - name: Package Firmware
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          echo "DEVICE_IP=$DEVICE_IP" >> $GITHUB_ENV

          cd ./lede && mkdir ./test
          cp -rf ./.config ./test/R4S_$BUILD_DATE.txt

      - name: Release Firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.DEVICE_NAME}}_Config_${{env.BUILD_DATE}}
          files: ./lede/test/*.txt
          body: |
            测试专用

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
