#CI项目
name: OWRT-ONE

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  #workflow_run:
    #workflows: ["Auto-Clean"]
    #types:
      #- completed
  #手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，仅限一个。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: MEDIATEK
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/immortalwrt/immortalwrt.git
      #源码分支
      WRT_BRANCH: master
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
