#CI项目名
name: Rockchip-Lede

on:
  #自动编译：每天早上4点
  schedule:
    - cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: Rockchip
      #默认主题
      WRT_THEME: design
      #默认主机名
      WRT_NAME: OWRT
      #默认密码，仅作展示，请勿乱改
      WRT_PW: password
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/coolsnowwolf/lede.git
      #默认分支
      WRT_BRANCH: master
