#CI项目
name: WRT-TEST

#CI计划
on:
  #手动编译
  workflow_dispatch:
    inputs:
      SOURCE:
        default: 'immortalwrt/immortalwrt'
        required: true
        type: choice
        options: [immortalwrt/immortalwrt, coolsnowwolf/lede, LiBwrt/openwrt-6.x, King-Of-Knights/openwrt-6.x]
      BRANCH:
        default: 'master'
        required: true
        type: string
      PACKAGE:
        default: 'CONFIG_PACKAGE_luci-app-dockerman=y'
        required: true
        type: string
      TARGET:
        default: 'Mediatek'
        required: true
        type: choice
        options: [Mediatek, Qualcom, Rockchip, X86]
      THEME:
        default: 'argon'
        required: true
        type: choice
        options: [argon, design]
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'true'
        required: true
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{inputs.TARGET}}
      #默认主题
      WRT_THEME: ${{inputs.THEME}}
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/${{inputs.SOURCE}}.git
      #默认分支
      WRT_BRANCH: ${{inputs.BRANCH}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST || 'false'}}
