#CI项目名
name: X64-Immortal

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台，X64包含X86
      WRT_TARGET: X64
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名
      WRT_WIFI: OWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #默认地址
      WRT_IP: 192.168.10.1
      #默认源码
      WRT_URL: https://github.com/immortalwrt/immortalwrt.git
      #默认分支
      WRT_BRANCH: master
